version: 2
models:
- name: stg_customers
  description: Bảng staging từ customers
  meta:
    vn_name: customers
    domain: ecommerce
  columns:
  - name: customer_id
    description: customer_id
    meta:
      vn_name: customer_id
      synonyms: []
    tests:
    - unique
    - not_null
  - name: customer_name
    description: customer_name
    meta:
      vn_name: customer_name
      synonyms: []
