version: 2
models:
- name: stg_orders
  description: Bảng staging từ orders
  meta:
    vn_name: orders
    domain: ecommerce
  columns:
  - name: order_id
    description: order_id
    meta:
      vn_name: order_id
      synonyms: []
    tests:
    - unique
    - not_null
  - name: order_date
    description: order_date
    meta:
      vn_name: order_date
      synonyms: []
  - name: total_amount
    description: total_amount
    meta:
      vn_name: total_amount
      synonyms: []
  - name: status
    description: status
    meta:
      vn_name: status
      synonyms: []
